### ISSUE TITLE
为什么要设置max_predictions_per_seq

### ISSUE THREAD

**Issue by zhanghaoie** [xu-song/bert_as_language_model#10]
如题

**Comment by zhanghaoie** [comment]
为什么概率要有15*20*21128的输出？

**Comment by zhanghaoie** [comment]
为什么概率要有?x20x21128的输出？

**Comment by xu-song** [comment]
通常情况下，mask掉一个词，预测这一个词，输出 `?x1x21128`，即`one_prediction_per_seq`。

但是对于多个subtoken，我采用的`whole word mask`，也就是mask 多个subtoken，也就有多个prediction。

在cpu上跑的话，`max_predictions_per_seq`建议设置更小一点，甚至设置成1。
