### ISSUE TITLE
原理是什么？

### ISSUE THREAD

**Issue by aaronliu7** [xu-song/bert_as_language_model#15]
看代码没看懂

**Comment by xu-song** [comment]
就是按顺序依次mask掉每一个词，然后预测该词的概率。
整个句子的概率就按照下面这个公式简单近似的:
![image](https://user-images.githubusercontent.com/13825126/92438908-5aff4780-f1dc-11ea-9243-3c5deebd1e15.png)

**Comment by aaronliu7** [comment]
> 就是按顺序依次mask掉每一个词，然后预测该词的概率。
> 整个句子的概率就按照下面这个公式简单近似的:
> ![image](https://user-images.githubusercontent.com/13825126/92438908-5aff4780-f1dc-11ea-9243-3c5deebd1e15.png)

明白了，感谢解答
