### ISSUE TITLE
online service的问题

### ISSUE THREAD

**Issue by aaronliu7** [xu-song/bert_as_language_model#16]
这个并没有fine-tune的模型，如何将bert-as-language-model作为线上服务呢？

**Comment by xu-song** [comment]
pretrain的模型可以直接用于 language model。

线上服务，需要自己在predict基础上包一个server

**Comment by aaronliu7** [comment]
> pretrain的模型可以直接用于 language model。
> 
> 线上服务，需要自己在predict基础上包一个server

没有那么多数据去重新pretrain。。。只能用google提供的中文预训练模型，调用run_lm_predict，想把run_lm_predict作为一个服务，请问这种的需要怎么操作呢？

**Comment by xu-song** [comment]
很多线上服务的方式，搜一下  `tensorflow 模型 部署`

最简单的用flask 搭个http server,
稳定点的还是用 tensorflow serving吧

**Comment by aaronliu7** [comment]
> 很多线上服务的方式，搜一下 `tensorflow 模型 部署`
> 
> 最简单的用flask 搭个http server

感谢解答
