### ISSUE TITLE
就是按顺序依次mask掉每一个词，然后预测该词的概率。

### ISSUE THREAD

**Issue by duan348733684** [xu-song/bert_as_language_model#17]
就是按顺序依次mask掉每一个词，然后预测该词的概率。
整个句子的概率就按照下面这个公式简单近似的:
![image](https://user-images.githubusercontent.com/13825126/92438908-5aff4780-f1dc-11ea-9243-3c5deebd1e15.png)

_Originally posted by @xu-song in https://github.com/xu-song/bert-as-language-model/issues/15#issuecomment-688638686_

请问最后的结果就是将预测的概率相乘？是这个意思吗?

**Comment by xu-song** [comment]
是的
这只是个简单近似

**Comment by duan348733684** [comment]
> 是的
> 这只是个简单近似

还有更复杂的近似吗？

**Comment by duan348733684** [comment]
> 是的
> 这只是个简单近似

谢谢

**Comment by xu-song** [comment]
严格一些的联合概率分布，应该需要GPT了
