### ISSUE TITLE
推导结果不正常

### ISSUE THREAD

**Issue by zhangyisheng0629** [xu-song/bert_as_language_model#19]
你哈，我从bert的[链接](https://storage.googleapis.com/bert_models/2020_02_20/uncased_L-12_H-768_A-12.zip)上下载了bert预训练模型，但是对于以下三句话的复杂度预测结果和你的差距有点大
而且第三句话的复杂度更小一些，这似乎不太正常
你知道什么这是原因吗，非常感谢~
我使用的tensorflow版本是2.6.2
[
  {
    "tokens": [
      {
        "token": "there",
        "prob": 0.002376210642978549
      },
      {
        "token": "is",
        "prob": 0.00032396349706687033
      },
      {
        "token": "a",
        "prob": 0.00016864163626451045
      },
      {
        "token": "book",
        "prob": 8.497028466081247e-05
      },
      {
        "token": "on",
        "prob": 0.000501244910992682
      },
      {
        "token": "the",
        "prob": 0.00038025222602300346
      },
      {
        "token": "desk",
        "prob": 6.700590802211082e-06
      }
    ],
    "ppl": 4931.9851396876575
  },
  {
    "tokens": [
      {
        "token": "there",
        "prob": 0.002963493810966611
      },
      {
        "token": "is",
        "prob": 0.0003500459424685687
      },
      {
        "token": "a",
        "prob": 0.00018642270879354328
      },
      {
        "token": "plane",
        "prob": 1.383832932333462e-05
      },
      {
        "token": "on",
        "prob": 0.0005545589956454933
      },
      {
        "token": "the",
        "prob": 0.00038116113864816725
      },
      {
        "token": "desk",
        "prob": 7.67214714869624e-06
      }
    ],
    "ppl": 5835.439745980134
  },
  {
    "tokens": [
      {
        "token": "there",
        "prob": 0.002954021329060197
      },
      {
        "token": "is",
        "prob": 0.00039738742634654045
      },
      {
        "token": "a",
        "prob": 0.00024926112382672727
      },
      {
        "token": "book",
        "prob": 0.00010113466123584658
      },
      {
        "token": "in",
        "prob": 0.00033981725573539734
      },
      {
        "token": "the",
        "prob": 0.00039128249045461416
      },
      {
        "token": "desk",
        "prob": 6.479389867308782e-06
      }
    ],
    "ppl": 4531.281922045702
  }
]

**Comment by xu-song** [comment]
https://huggingface.co/spaces/eson/bert-perplexity  这里有个demo，可以直接测试。或者clone下来直接运行

**Comment by zhangyisheng0629** [comment]
thanks!
