### ISSUE TITLE
作为language model对句子打分需要finetune吗

### ISSUE THREAD

**Issue by HyacinthJingjing** [xu-song/bert_as_language_model#2]
如果把bert作为语言模型，来对句子进行rescore，是相当于token classification任务是吧，是需要在BertModel的基础上加上一个线性层（如linear[hidden_size, vocab_size])，然后进行finetune吗

**Comment by xu-song** [comment]
不需要finetune，线性层在pretrain_model里是包含的

**Comment by HyacinthJingjing** [comment]
做语言模型打分，如果直接输入整句话，不做mask，这样做可以吗

**Comment by xu-song** [comment]
不可以
