### ISSUE TITLE
请问模型微调过吗? 

### ISSUE THREAD

**Issue by RumRaisins** [xu-song/bert_as_language_model#20]
用uncased_L-12_H-768_A-12,chinese_L-12_H-768_A-12  跑不出来效果

**Comment by xu-song** [comment]
没微调，可以看这里的demo
https://huggingface.co/spaces/eson/bert-perplexity

**Comment by RumRaisins** [comment]
请问 init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt   这个参数是什么?
我下载到模型 没有bert_model.ckpt ,     只有 bert_model.ckpt.data-00000-of-00001  bert_model.ckpt.index  bert_model.ckpt.meta  config.json  vocab.txt
请问有可能是这个问题吗?

**Comment by RumRaisins** [comment]
sorry,大佬. 我的问题 模型读错了.   感谢大佬回复
