### ISSUE TITLE
Export bert-as-language-model as online service but failed.

### ISSUE THREAD

**Issue by stevewyl** [xu-song/bert_as_language_model#3]
Hi, I'm trying to export the unfine-tuned BERT model as online service. 
I followed the official instructions [SavedModel](https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators) and successfully exported the fine-tuned model. But when I try to export the original BERT model, it failed. The error messages are as followed:

Traceback (most recent call last):
File "export_lm_predictor.py", line 136, in 
'./exported_model', serving_input_receiver_fn(max_seq_len, 20))
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 734, in export_saved_model
strip_default_attrs=True)
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 663, in export_savedmodel
mode=model_fn_lib.ModeKeys.PREDICT)
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 789, in _export_saved_model_for_mode
strip_default_attrs=strip_default_attrs)
File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 878, in _export_all_saved_models
raise ValueError("Couldn't find trained model at %s." % self._model_dir)
ValueError: Couldn't find trained model at ../bert_models/chinese_L-12_H-768_A-12.

I guess that there is no graph.pbtxt and checkpoint files in the original model dir. Does anyone have any ideas? Thanks!

[edit]
I specify the checkpoint_path parameter in export_saved_model function. By the way, I
create the estimator using tf.estimator.Estimator. Then I got a new error:
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory ../bert_models/chinese_L-12_H-768_A-12
So we must got checkpoint file in the original BERT model directory?

**Comment by xu-song** [comment]
`bert_model.ckpt.meta` is the graph, no `pbtxt`.

You can export meta graph as `pb` using the following script

```
TRAIN_DIR=bert_models/chinese_L-12_H-768_A-12
freeze_graph \
    --input_meta_graph=${TRAIN_DIR}/bert_model.ckpt.meta \
    --input_binary=true \
    --input_checkpoint=${TRAIN_DIR}/bert_model.ckpt \
    --output_graph=${TRAIN_DIR}/frozen_graph.pb \
    --output_node_names=...
```

**Comment by stevewyl** [comment]
@xu-song Thanks! I got it, I need to freeze the model first. Another question, with regard to "output_node_names", I checked the node names of bert and found over 3000 nodes. So I must pass all these node names to this argument or just the last node of the graph?

**Comment by xu-song** [comment]
just the last node, which depends on your task
