### ISSUE TITLE
字prob和句子perplexity计算方法

### ISSUE THREAD

**Issue by lxylxyoo** [xu-song/bert_as_language_model#5]
你好，感谢你提供了使用bert计算perplexity的代码。
目前我有两个小疑问希望能得到解答：
1、计算某个字的prob时是不是首先对该字进行mask，然后输入mask后的句子，再对mask位置的隐层向量进行softmax从而得到该字的prob。通过对句中所有字进行上述遍历，遍得到了句中所有字的prob？
2、是否会计算[CLS]和[SEP]的prob？计算perplexity时是否会考虑[CLS]和[SEP]的prob，还是只考虑原始句子中所有字的prob？
感谢！

**Comment by xu-song** [comment]
1. 是的
1. 不计算[CLS] [SEP]的prob，计算perplexity也不考虑[CLS] [SEP],  具体例子你可以看 https://github.com/xu-song/bert-as-language-model/blob/master/data/lm/result.zh.json#L1 。
这里有每个字的prob，整个句子的perplexity

**Comment by lxylxyoo** [comment]
谢谢！
