### ISSUE TITLE
每次执行时提示找不到模型

### ISSUE THREAD

**Issue by barry1006** [xu-song/bert_as_language_model#7]
INFO:tensorflow:Could not find trained model in model_dir: ./bert_output, running initialization to predict.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Running infer on CPU
INFO:tensorflow:Initialize variable bert/embeddings/LayerNorm/beta:0 from checkpoint 

参数指定了 output_dir作为导出的模型保存路径，  不过导出为空。封装成函数去调用， 每次调用预测函数 estimator.predict，  都要从google的中文模型中重新加载， 重新走到    Could not find trained model in model_dir: ./bert_output, running initialization to predict.

**Comment by xu-song** [comment]
你要在bert官方下载 model。

[BERT-Base, Chinese](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip)  这是官方的中文模型

**Comment by barry1006** [comment]
模型加载了， chinese那个380M的，  通过init_checkpoint参数把模型地址传进去的。  可以正确给句子打分，结果输出都没问题。
中间过程， 比较慢：
原因1：  加载模型时候，每次都提示找不到模型，从checkpoint重新加载。参数output_dir  传递也没问题，  但是output_dir中没有正确导出模型。
原因2： 在parse_result时，  遍历result， 把每次遍历的时间戳打出来，发现有的每次间隔5~8个token会出现一次特别慢的， 导致 每次parse一个句子需要耗时1秒。  


------------------
 Best Regards,
yangzzhao 赵阳 Barry Z.
Tencent
 Mobile:18503058640




 




------------------ Original ------------------

**Comment by barry1006** [comment]
> 你要在bert官方下载 model。
> 
> [BERT-Base, Chinese](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip) 这是官方的中文模型

模型加载了， chinese那个380M的，  通过init_checkpoint参数把模型地址传进去的。  可以正确给句子打分，结果输出都没问题。
中间过程， 比较慢：
原因1：  加载模型时候，每次都提示找不到模型，从checkpoint重新加载。参数output_dir  传递也没问题，  但是output_dir中没有正确导出模型。
原因2： 在parse_result时，  遍历result， 把每次遍历的时间戳打出来，发现有的每次间隔5~8个token会出现一次特别慢的， 导致 每次parse一个句子需要耗时1秒。

不懂为什么有的token遍历很快，有的却很慢达到200毫秒以上，有什么方法可以提高parse result的性能吗，谢谢！

**Comment by xu-song** [comment]
1.  找不到模型，，，不清楚原因

2. parse_result的逻辑很简单，应该很快的。

**Comment by xu-song** [comment]
1.  找不到模型，，，不清楚原因。是不是tensorflow版本的问题。

2. 因为tensorflow采用的延迟计算，默认的[batch_size是8](https://github.com/xu-song/bert-as-language-model/blob/master/run_lm_predict.py#L427)，每隔8个token会真正运行第一次predict graph

**Comment by barry1006** [comment]
谢谢！！！
对于问题2，   默认的batch_size是8，每隔8个token会真正运行第一次predict graph，  能否通过调整batch size， 让平均起来性能更好。
目前预测一句话大约需要将近1秒。








------------------
 Best Regards,
yangzzhao 赵阳 Barry Z.
Tencent
 Mobile:18503058640




 




------------------ Original ------------------

**Comment by BitMindLab** [comment]
把 batch_size 尽可能调大

**Comment by xu-song** [comment]
batch size尽可能调大，用GPU跑。

用bert跑语言模型，这种方式计算量太大，不太适合线上服务。

**Comment by boy-be-ambitious** [comment]
> > 你要在bert官方下载 model。
> > [BERT-Base, Chinese](https://storage.googleapis.com/bert_models/2018_11_03/chinese_L-12_H-768_A-12.zip) 这是官方的中文模型
> 
> 模型加载了， chinese那个380M的， 通过init_checkpoint参数把模型地址传进去的。 可以正确给句子打分，结果输出都没问题。
> 中间过程， 比较慢：
> 原因1： 加载模型时候，每次都提示找不到模型，从checkpoint重新加载。参数output_dir 传递也没问题， 但是output_dir中没有正确导出模型。
> 原因2： 在parse_result时， 遍历result， 把每次遍历的时间戳打出来，发现有的每次间隔5~8个token会出现一次特别慢的， 导致 每次parse一个句子需要耗时1秒。
> 
> 不懂为什么有的token遍历很快，有的却很慢达到200毫秒以上，有什么方法可以提高parse result的性能吗，谢谢！

您好，想问下没有正确导出模型这个最后解决了吗，如何解决的呢

**Comment by Tiankekeke** [comment]
Could not find trained model in model_dir: lm_output/, running initialization to predict.
您好，用的Google的官方模型，设置和你的一模一样，为什么还会报这个错呢？

**Comment by alphadl** [comment]
@xu-song 作者您好~ 我把你的代码改成了tf2.0的，加载同样的中文模型，同样的例句，结果每个词的prob非常低，大概都是0.000*，ppl非常高~ 可以提供点建议么

**Comment by alphadl** [comment]
@xu-song 如下所示：
![image](https://user-images.githubusercontent.com/20458732/78987476-bdd2b100-7b60-11ea-8854-36182b9a4f06.png)

**Comment by xu-song** [comment]
你确定用的是相同的模型吗？没试过2.0

**Comment by alphadl** [comment]
是相同的模型哎~
